add entity and typeORM
Mi4-04/movies-server pull request #1
Opened 2022-03-04 13:36 UTC by Mi4-04

-add entities modules fav-movies user genres
-add migration

2022-03-04 17:34 UTC, Isidora25 requested changes

2022-03-04 17:34 UTC, Isidora25 commented on src/config/typeorm.config.ts
> +  password: 'asdasd04281',
Данные для  подключения к БД нельзя хранить в коде в открытом доступе, вынеси в энвы

2022-03-04 17:34 UTC, Isidora25 commented on src/genres/genres.entity.ts
> +  user: UserEntity;
А что будет храниться в `user`? Связь с только с одним юзером?
Кажется один жанр может быть связан со многими юзерами 
А еще вопрос, почему именно с юзерами? Кажется, что жанр - это какое-то свойство фильма, а не юзера?

2022-03-04 17:34 UTC, Isidora25 commented on src/genres/genres.entity.ts
> +  genre_id: number;
имена полей энтити пишутся в camelCase

2022-03-04 17:34 UTC, Isidora25 commented on src/fav-movies/fav-movies.entity.ts
> +  movies_id: number;
имена полей энтити пишутся в camelCase

2022-03-04 17:34 UTC, Isidora25 commented on src/fav-movies/fav-movies.entity.ts
> +  createDate: string;
Для дат есть специальный тип Date

2022-03-04 17:34 UTC, Isidora25 commented on src/migrations/1646395856382-init.ts
> +  public async up(queryRunner: QueryRunner): Promise<void> {}
Что делает эта миграция?

2022-03-04 17:34 UTC, Isidora25 commented on src/genres/genres.entity.ts
> +  genre_id: number;
А чем отличается genre_id и id?

2022-03-05 17:59 UTC, Mi4-04 commented on src/migrations/1646395856382-init.ts
> +  public async up(queryRunner: QueryRunner): Promise<void> {}
Иницилизация бд

2022-03-05 18:00 UTC, Mi4-04 commented on src/genres/genres.entity.ts
> +  genre_id: number;
id  там по счетчику идет по номеру в таблице в genre_id это есть id в апи у самих жанров их хранить как раз

2022-03-05 18:01 UTC, Mi4-04 commented on src/genres/genres.entity.ts
> +  user: UserEntity;
Один user может выбрать несколько жанров,
и один user может выбрать много favMovies

2022-03-05 18:01 UTC, Mi4-04 commented on src/config/typeorm.config.ts
> +  password: 'asdasd04281',
Да забыл вынести, сорян

2022-03-09 10:44 UTC, Isidora25 requested changes

2022-03-09 10:44 UTC, Isidora25 commented on src/config/typeorm.config.ts
> +    database: process.env.TYPEORM_DATABASE,
Вместо всех этих параметров можно использовать один, url

2022-03-09 10:44 UTC, Isidora25 commented on src/genres/genres.entity.ts
>    @Column()
{name: genre_id}

2022-03-09 11:55 UTC, Isidora25 approved these changes

2022-03-09 11:55 UTC, merged