add page argument in getAllMovies serivce
Mi4-04/movies-server pull request #4
Opened 2022-03-29 08:31 UTC by Mi4-04

fix service setWatchedMovie and removeMovie

2022-03-29 10:43 UTC, Isidora25 requested changes

2022-03-29 10:43 UTC, Isidora25 commented on src/fav-movies/dto/fav-movies.dto.ts
> +  original_language: string;
У тебя получается цирк с именованием переменных, где-то snake_case, где-то camelCase
Попробуй указать в параметрах для field { name: camelCaseName }, тогда в схему будет попадать все в правильном формате

2022-03-29 13:59 UTC, Isidora25 approved these changes

2022-03-30 06:34 UTC, reshetov approved these changes

2022-03-31 13:02 UTC, Isidora25 requested changes

2022-03-31 13:02 UTC, Isidora25 commented on src/user/user.service.ts
> +  async getFavMovies({
А почему это юзер сервис? Какие действия с юзером здесь происходят?

2022-03-31 13:02 UTC, Isidora25 commented on src/user/user.service.ts
> +      where: { user: user },
where - лишний
Ты прямо по всем объекту юзера делаешь поиск? 
Не проще ли только по одному полю? например по id или email?

2022-03-31 13:02 UTC, Isidora25 commented on src/user/user.service.ts
> +      return result;
а что ты тут проверяешь? где асинхронный вызов функции?

2022-03-31 13:02 UTC, Isidora25 commented on src/user/user.service.ts
> +        let movieIdData = lastValueFrom(moviesDetails.pipe(map((res) => res)));
Что делает pipe?

2022-04-01 06:54 UTC, Isidora25 commented on src/fav-movies/fav-movies.module.ts
> +    UsersModule,
А модуль зачем?

2022-04-01 06:59 UTC, Isidora25 requested changes

2022-04-01 06:59 UTC, Isidora25 commented on src/fav-movies/fav-movies.module.ts
> -    UsersModule,
А импорт модуля кому оставил?

2022-04-01 07:03 UTC, Isidora25 approved these changes

2022-04-01 07:48 UTC, reshetov requested changes

2022-04-01 07:48 UTC, reshetov commented on src/fav-movies/fav-movies.service.ts
> +    favMoviesEntity.moviesId = id;
А точно нужно каждый раз по одному атрибуту менять? (это я к тому что если у тебя модель из 30 аттрибутов то код будет в виде портянки. Попробуй переделать на сразу массовое присвоение

2022-04-01 07:48 UTC, reshetov commented on src/fav-movies/fav-movies.service.ts
> +      throw new InternalServerErrorException();
Чет так себе обработка ошибки - если что-то пошло не так перехватить ошибку и сгенерировать такую-же только новую)

2022-04-01 07:48 UTC, reshetov commented on src/fav-movies/fav-movies.service.ts
> +      throw new InternalServerErrorException();
см. выше

2022-04-01 07:48 UTC, reshetov commented on src/fav-movies/fav-movies.service.ts
> +      throw new BadRequestException('Movie not found');
У тебя есть локали тут?

2022-04-01 07:48 UTC, reshetov commented on src/fav-movies/fav-movies.service.ts
> +
Чисто оформительское - лишняя строка

2022-04-01 13:37 UTC, reshetov approved these changes

2022-04-01 13:38 UTC, Isidora25 requested changes

2022-04-01 13:38 UTC, Isidora25 commented on src/fav-movies/fav-movies.service.ts
> +    const favMoviesEntity = this.favMoviesRepository.manager.create(
Используй сразу save

2022-04-01 13:59 UTC, Isidora25 approved these changes

2022-04-04 11:55 UTC, merged